### PR TITLE
removed state

### PR DESCRIPTION
**Pull request by educastellano**
So it will render when we change the routes prop... :)

### CODE REVIEW

**Comment by asbjornenge** [comment]
Hmm... For one thing I wonder if `forceUpdate` has any bad side-effects we should look to avoid for a top-level component like this? It's usually the outer most component I have in my apps. Have you looked into that? Seems a bit "bruteforce" :stuck_out_tongue_closed_eyes: 

Secondly, would not something like this solve your problem?

``` js
class App extends ReactComponent {
  constructor() {
    this.state = {
      routes = {} // <- routes here
    }
  }
  render() {
    return (
      <Router routes={this.state.routes} />
    )
  }
}

ReactDOM.render(<App />, node)
```

**Comment by educastellano** [comment]
That wouldn't work because the Router is keeping another state inside... Another solution is to update the state when `componentWillReceiveProps()`

But anyways, I found another (and better) solution in my app, by just rendering the Router once. You can just drop this... <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:67.5% 0%;background-size:4100%" title="stuck_out_tongue"></span></span> 😛   👉👈 

About `forceUpdate()`, to my understanding it has the same effect as `setState()` just that it's meant to be used in special cases, like this one where we need to update the component when the hash changes: 

https://facebook.github.io/react/docs/component-api.html#forceupdate

I guess they say you should avoid it just to make you use the "normal flow" of a React app...

**Comment by asbjornenge** [comment]
@educastellano I'm putting this on my _tofix_ list when I get back. Haven't looked at code for like a month, so I'm totally rusty already :stuck_out_tongue_closed_eyes: I think the `Router` should re-render if we change the `routes` prop. It makes sense.

**Comment by educastellano** [comment]
haha np 😄👍

**Pull request closed without merging**
